all:
  hosts:
    remote_server:
      ansible_host: 172.10.12.55  # Replace with your server's IP or hostname
      ansible_user: ubuntu         # Replace with your SSH user
      # ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Optional: Path to SSH keyls
      